project_id = "unngatxeencjfnqaqbld"

[functions.submit-form]
verify_jwt = false

[functions.shopify-storefront]
verify_jwt = false

[functions.track-events]
verify_jwt = false

[functions.identify-user]
verify_jwt = false

[functions.analytics-dashboard]
verify_jwt = false

