// ============================================
// SERA NORR Stone Library - Full Catalog from PDFs
// ============================================
// Source: Travertine_collection_tostone.pdf & Marble_stone_collection_tostone.pdf

export type StoneFamily = 'travertine' | 'marble';
export type StoneTier = 'signature' | 'atelier' | 'icon';
export type StoneCollection = 'terra' | 'vanta' | 'core';
export type CharacterTag = 'warm' | 'cool' | 'calm' | 'dramatic' | 'veined' | 'porous' | 'statement';

export interface StoneLibraryEntry {
  id: string;
  name: string;
  family: StoneFamily;
  collection: StoneCollection;
  tier: StoneTier;
  finishOptions: ('honed' | 'polished' | 'matte')[];
  shortDescription: string;
  characterTags: CharacterTag[];
  swatchColor: string; // Fallback color for swatch
  swatchImage?: string; // Optional image path for swatch
  isActiveInConfigurator: boolean;
  sortOrder: number;
}

// ============================================
// TRAVERTINE COLLECTION (from Travertine PDF)
// ============================================
const TRAVERTINE_STONES: StoneLibraryEntry[] = [
  {
    id: 'gore-gray',
    name: 'Gore Gray',
    family: 'travertine',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Sophisticated grey with subtle veining',
    characterTags: ['cool', 'calm'],
    swatchColor: '#8B8B8B',
    swatchImage: '/stones/travertine/gore-gray.jpg',
    isActiveInConfigurator: true,
    sortOrder: 1,
  },
  {
    id: 'ivory',
    name: 'Ivory',
    family: 'travertine',
    collection: 'terra',
    tier: 'signature',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Classic warm ivory with natural character',
    characterTags: ['warm', 'calm', 'porous'],
    swatchColor: '#FFFFF0',
    swatchImage: '/stones/travertine/ivory.jpg',
    isActiveInConfigurator: true,
    sortOrder: 2,
  },
  {
    id: 'super-white-travertine',
    name: 'Super White',
    family: 'travertine',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Bright white travertine, pure elegance',
    characterTags: ['cool', 'calm'],
    swatchColor: '#FAFAFA',
    swatchImage: '/stones/travertine/super-white.jpg',
    isActiveInConfigurator: true,
    sortOrder: 3,
  },
  {
    id: 'cream-travertine',
    name: 'Cream',
    family: 'travertine',
    collection: 'terra',
    tier: 'signature',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Soft creamy tones with gentle warmth',
    characterTags: ['warm', 'calm'],
    swatchColor: '#FFFDD0',
    swatchImage: '/stones/travertine/cream.jpg',
    isActiveInConfigurator: true,
    sortOrder: 4,
  },
  {
    id: 'river-silver',
    name: 'River Silver',
    family: 'travertine',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Silver-grey with flowing veins',
    characterTags: ['cool', 'veined'],
    swatchColor: '#C0C0C0',
    swatchImage: '/stones/travertine/river-silver.jpg',
    isActiveInConfigurator: true,
    sortOrder: 5,
  },
  {
    id: 'brown-silver',
    name: 'Brown Silver',
    family: 'travertine',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Warm brown with silver undertones',
    characterTags: ['warm', 'veined'],
    swatchColor: '#A08060',
    swatchImage: '/stones/travertine/brown-silver.jpg',
    isActiveInConfigurator: true,
    sortOrder: 6,
  },
  {
    id: 'titanium-silver',
    name: 'Titanium Silver',
    family: 'travertine',
    collection: 'core',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Industrial silver with bold character',
    characterTags: ['cool', 'statement'],
    swatchColor: '#A0A0A0',
    swatchImage: '/stones/travertine/titanium-silver.jpg',
    isActiveInConfigurator: true,
    sortOrder: 7,
  },
  {
    id: 'sbyss-black',
    name: 'SBYSS Black',
    family: 'travertine',
    collection: 'vanta',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Rare black travertine, dramatic depth',
    characterTags: ['cool', 'dramatic', 'statement'],
    swatchColor: '#1A1A1A',
    swatchImage: '/stones/travertine/sbyss-black.jpg',
    isActiveInConfigurator: true,
    sortOrder: 8,
  },
  {
    id: 'golden-coast',
    name: 'Golden Coast',
    family: 'travertine',
    collection: 'terra',
    tier: 'signature',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Sun-kissed gold with natural warmth',
    characterTags: ['warm', 'veined'],
    swatchColor: '#DAA520',
    swatchImage: '/stones/travertine/golden-coast.jpg',
    isActiveInConfigurator: true,
    sortOrder: 9,
  },
  {
    id: 'classic-cloudy',
    name: 'Classic Cloudy',
    family: 'travertine',
    collection: 'terra',
    tier: 'signature',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Soft clouds of beige and cream',
    characterTags: ['warm', 'calm'],
    swatchColor: '#E8DFD0',
    swatchImage: '/stones/travertine/classic-cloudy.jpg',
    isActiveInConfigurator: true,
    sortOrder: 10,
  },
  {
    id: 'classic-light',
    name: 'Classic Light',
    family: 'travertine',
    collection: 'terra',
    tier: 'signature',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Light and airy natural stone',
    characterTags: ['warm', 'calm'],
    swatchColor: '#F5F0E6',
    swatchImage: '/stones/travertine/classic-light.jpg',
    isActiveInConfigurator: true,
    sortOrder: 11,
  },
  {
    id: 'soft-rome',
    name: 'Soft Rome',
    family: 'travertine',
    collection: 'terra',
    tier: 'atelier',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Roman elegance in soft earth tones',
    characterTags: ['warm', 'calm', 'porous'],
    swatchColor: '#D4C4B0',
    swatchImage: '/stones/travertine/soft-rome.jpg',
    isActiveInConfigurator: true,
    sortOrder: 12,
  },
  {
    id: 'sivas-yellow',
    name: 'Sivas Yellow',
    family: 'travertine',
    collection: 'terra',
    tier: 'atelier',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Warm yellow with Turkish heritage',
    characterTags: ['warm', 'veined'],
    swatchColor: '#F0D58C',
    swatchImage: '/stones/travertine/sivas-yellow.jpg',
    isActiveInConfigurator: true,
    sortOrder: 13,
  },
  {
    id: 'tiramisu',
    name: 'Tiramisu',
    family: 'travertine',
    collection: 'terra',
    tier: 'signature',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Rich coffee tones, naturally layered',
    characterTags: ['warm', 'veined', 'statement'],
    swatchColor: '#E8DFD0',
    swatchImage: '/stones/travertine/tiramisu.jpg',
    isActiveInConfigurator: true,
    sortOrder: 14,
  },
  {
    id: 'swamp-brown',
    name: 'Swamp Brown',
    family: 'travertine',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'matte'],
    shortDescription: 'Deep earthy brown with character',
    characterTags: ['warm', 'dramatic'],
    swatchColor: '#4A3C28',
    swatchImage: '/stones/travertine/swamp-brown.jpg',
    isActiveInConfigurator: true,
    sortOrder: 15,
  },
  {
    id: 'antique-red',
    name: 'Antique Red',
    family: 'travertine',
    collection: 'core',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Rare red travertine with ancient patina',
    characterTags: ['warm', 'dramatic', 'statement'],
    swatchColor: '#8B4513',
    swatchImage: '/stones/travertine/antique-red.jpg',
    isActiveInConfigurator: true,
    sortOrder: 16,
  },
  {
    id: 'leonardo-travertine',
    name: 'Leonardo Travertine',
    family: 'travertine',
    collection: 'terra',
    tier: 'signature',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Renaissance-inspired warm elegance',
    characterTags: ['warm', 'calm'],
    swatchColor: '#D2B48C',
    swatchImage: '/stones/travertine/leonardo.jpg',
    isActiveInConfigurator: true,
    sortOrder: 17,
  },
  {
    id: 'light-cream-travertine',
    name: 'Light Cream Travertine',
    family: 'travertine',
    collection: 'terra',
    tier: 'signature',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Delicate cream with subtle pores',
    characterTags: ['warm', 'calm', 'porous'],
    swatchColor: '#FDF5E6',
    swatchImage: '/stones/travertine/cream.jpg',
    isActiveInConfigurator: true,
    sortOrder: 18,
  },
  {
    id: 'cream-beige-travertine',
    name: 'Cream Beige Travertine',
    family: 'travertine',
    collection: 'terra',
    tier: 'signature',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Classic beige with creamy undertones',
    characterTags: ['warm', 'calm'],
    swatchColor: '#E8D8C8',
    swatchImage: '/stones/travertine/classic-light.jpg',
    isActiveInConfigurator: true,
    sortOrder: 19,
  },
  {
    id: 'silver-grey-travertine',
    name: 'Silver Grey Travertine',
    family: 'travertine',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Cool silver grey with natural depth',
    characterTags: ['cool', 'calm'],
    swatchColor: '#A9A9A9',
    swatchImage: '/stones/travertine/river-silver.jpg',
    isActiveInConfigurator: true,
    sortOrder: 20,
  },
  {
    id: 'jurassico-scurro-travertine',
    name: 'Jurassico Scurro Travertine',
    family: 'travertine',
    collection: 'core',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Dark prehistoric character, rare find',
    characterTags: ['cool', 'dramatic', 'statement'],
    swatchColor: '#4A4A4A',
    swatchImage: '/stones/travertine/swamp-brown.jpg',
    isActiveInConfigurator: true,
    sortOrder: 21,
  },
  {
    id: 'novona-travertine',
    name: 'Novona Travertine',
    family: 'travertine',
    collection: 'terra',
    tier: 'atelier',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Modern travertine, refined texture',
    characterTags: ['warm', 'calm'],
    swatchColor: '#C4B8A8',
    swatchImage: '/stones/travertine/soft-rome.jpg',
    isActiveInConfigurator: true,
    sortOrder: 22,
  },
];

// ============================================
// MARBLE COLLECTION (from Marble PDF)
// ============================================
const MARBLE_STONES: StoneLibraryEntry[] = [
  // White/Light Marbles
  {
    id: 'calacatta-vagli',
    name: 'Calacatta Vagli',
    family: 'marble',
    collection: 'vanta',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Italian masterpiece, bold golden veins',
    characterTags: ['warm', 'veined', 'statement'],
    swatchColor: '#F5F5F0',
    swatchImage: '/stones/marble/calacatta-vagli.jpg',
    isActiveInConfigurator: true,
    sortOrder: 1,
  },
  {
    id: 'bianco-carrara',
    name: 'Bianco Carrara',
    family: 'marble',
    collection: 'core',
    tier: 'signature',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Timeless Italian white marble',
    characterTags: ['cool', 'veined', 'calm'],
    swatchColor: '#F0F0F0',
    swatchImage: '/stones/marble/bianco-carrara.jpg',
    isActiveInConfigurator: true,
    sortOrder: 2,
  },
  {
    id: 'volakas-white',
    name: 'Volakas White',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Greek white with grey veining',
    characterTags: ['cool', 'veined'],
    swatchColor: '#EEEEE8',
    swatchImage: '/stones/marble/volakas-white.jpg',
    isActiveInConfigurator: true,
    sortOrder: 3,
  },
  {
    id: 'super-white-marble',
    name: 'Super White',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Brilliant white, clean appearance',
    characterTags: ['cool', 'calm'],
    swatchColor: '#FFFFFF',
    swatchImage: '/stones/marble/super-white-marble.jpg',
    isActiveInConfigurator: true,
    sortOrder: 4,
  },
  {
    id: 'panda-white',
    name: 'Panda White',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Striking black and white contrast',
    characterTags: ['cool', 'dramatic', 'veined'],
    swatchColor: '#F0F0F0',
    swatchImage: '/stones/marble/panda-white.jpg',
    isActiveInConfigurator: true,
    sortOrder: 5,
  },
  {
    id: 'star-white-marble',
    name: 'Star White Marble',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Stellar white with subtle sparkle',
    characterTags: ['cool', 'calm'],
    swatchColor: '#FAFAFA',
    swatchImage: '/stones/marble/star-white.jpg',
    isActiveInConfigurator: true,
    sortOrder: 6,
  },
  {
    id: 'wooden-white-marble',
    name: 'Wooden White Marble',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Wood-like veins in white marble',
    characterTags: ['warm', 'veined'],
    swatchColor: '#F5F0E8',
    swatchImage: '/stones/marble/wooden-white.jpg',
    isActiveInConfigurator: true,
    sortOrder: 7,
  },
  
  // Arabescato Family
  {
    id: 'arabescato-corchia',
    name: 'Arabescato Corchia',
    family: 'marble',
    collection: 'vanta',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Dramatic arabesque veining',
    characterTags: ['cool', 'dramatic', 'veined', 'statement'],
    swatchColor: '#F0EDE8',
    swatchImage: '/stones/marble/arabescato-corchia.jpg',
    isActiveInConfigurator: true,
    sortOrder: 8,
  },
  {
    id: 'arabescato-vagli',
    name: 'Arabescato Vagli',
    family: 'marble',
    collection: 'vanta',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Tuscan elegance with bold veins',
    characterTags: ['cool', 'dramatic', 'veined', 'statement'],
    swatchColor: '#F2EFE8',
    swatchImage: '/stones/marble/arabescato-vagli.jpg',
    isActiveInConfigurator: true,
    sortOrder: 9,
  },
  {
    id: 'dark-arabescato-orobico',
    name: 'Dark Arabescato Orobico',
    family: 'marble',
    collection: 'vanta',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Dark dramatic with silver veins',
    characterTags: ['cool', 'dramatic', 'statement'],
    swatchColor: '#3A3A3A',
    swatchImage: '/stones/marble/dark-arabescato-orobico.jpg',
    isActiveInConfigurator: true,
    sortOrder: 10,
  },
  {
    id: 'arabella',
    name: 'Arabella',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Soft arabesque pattern, refined',
    characterTags: ['warm', 'veined'],
    swatchColor: '#E8E0D8',
    swatchImage: '/stones/marble/arabella.jpg',
    isActiveInConfigurator: true,
    sortOrder: 11,
  },
  
  // Calacatta Family
  {
    id: 'calacatta-rosa',
    name: 'Calacatta Rosa',
    family: 'marble',
    collection: 'vanta',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Blush pink veins on white',
    characterTags: ['warm', 'veined', 'statement'],
    swatchColor: '#F8F0F0',
    swatchImage: '/stones/marble/calacatta-rosa.jpg',
    isActiveInConfigurator: true,
    sortOrder: 12,
  },
  {
    id: 'calacatta-viola',
    name: 'Calacatta Viola',
    family: 'marble',
    collection: 'vanta',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Rare purple veins, ultimate luxury',
    characterTags: ['cool', 'dramatic', 'veined', 'statement'],
    swatchColor: '#F5F0F5',
    swatchImage: '/stones/marble/calacatta-viola.jpg',
    isActiveInConfigurator: true,
    sortOrder: 13,
  },
  {
    id: 'calacatta-verde-monet',
    name: 'Calacatta Verde Monet',
    family: 'marble',
    collection: 'vanta',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Green impressionist masterpiece',
    characterTags: ['cool', 'veined', 'statement'],
    swatchColor: '#E8F0E8',
    swatchImage: '/stones/marble/calacatta-verde-monet.jpg',
    isActiveInConfigurator: true,
    sortOrder: 14,
  },
  
  // Green Marbles & Quartzites
  {
    id: 'verde-alpi',
    name: 'Verde Alpi',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Alpine green with white veins',
    characterTags: ['cool', 'veined', 'statement'],
    swatchColor: '#2D4A3E',
    swatchImage: '/stones/marble/verde-alpi.jpg',
    isActiveInConfigurator: true,
    sortOrder: 15,
  },
  {
    id: 'verde-affai',
    name: 'Verde Affai',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Rich forest green marble',
    characterTags: ['cool', 'dramatic'],
    swatchColor: '#355E3B',
    swatchImage: '/stones/marble/verde-alpi.jpg',
    isActiveInConfigurator: true,
    sortOrder: 16,
  },
  {
    id: 'amazon-green-quartzite',
    name: 'Amazon Green Quartzite',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Exotic green from the Amazon',
    characterTags: ['cool', 'dramatic', 'statement'],
    swatchColor: '#228B22',
    swatchImage: '/stones/marble/amazon-green.jpg',
    isActiveInConfigurator: true,
    sortOrder: 17,
  },
  {
    id: 'roval-green-quartzite',
    name: 'Roval Green Quartzite',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Royal green with subtle veins',
    characterTags: ['cool', 'veined'],
    swatchColor: '#3D6B4F',
    swatchImage: '/stones/marble/amazon-green.jpg',
    isActiveInConfigurator: true,
    sortOrder: 18,
  },
  {
    id: 'maestro-green-quartzite',
    name: 'Maestro Green Quartzite',
    family: 'marble',
    collection: 'core',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Masterful green statement piece',
    characterTags: ['cool', 'dramatic', 'statement'],
    swatchColor: '#4A7C59',
    swatchImage: '/stones/marble/verde-alpi.jpg',
    isActiveInConfigurator: true,
    sortOrder: 19,
  },
  {
    id: 'avocado-quartzite',
    name: 'Avocado Quartzite',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Fresh avocado green tones',
    characterTags: ['warm', 'calm'],
    swatchColor: '#568203',
    swatchImage: '/stones/marble/amazon-green.jpg',
    isActiveInConfigurator: true,
    sortOrder: 20,
  },
  {
    id: 'emerald-jade-marble',
    name: 'Emerald Jade Marble',
    family: 'marble',
    collection: 'vanta',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Precious emerald jade tones',
    characterTags: ['cool', 'dramatic', 'statement'],
    swatchColor: '#50C878',
    swatchImage: '/stones/marble/emerald-jade.jpg',
    isActiveInConfigurator: true,
    sortOrder: 21,
  },
  {
    id: 'jade-river',
    name: 'Jade River',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Flowing jade river patterns',
    characterTags: ['cool', 'veined'],
    swatchColor: '#00A86B',
    swatchImage: '/stones/marble/emerald-jade.jpg',
    isActiveInConfigurator: true,
    sortOrder: 22,
  },
  {
    id: 'green-onyx',
    name: 'Green Onyx',
    family: 'marble',
    collection: 'vanta',
    tier: 'icon',
    finishOptions: ['polished'],
    shortDescription: 'Translucent green onyx luxury',
    characterTags: ['cool', 'dramatic', 'statement'],
    swatchColor: '#3CB371',
    swatchImage: '/stones/marble/green-onyx.jpg',
    isActiveInConfigurator: true,
    sortOrder: 23,
  },
  {
    id: 'ceppo-verde',
    name: 'Ceppo Verde',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Green terrazzo-style conglomerate',
    characterTags: ['cool', 'dramatic'],
    swatchColor: '#4F7942',
    swatchImage: '/stones/marble/verde-alpi.jpg',
    isActiveInConfigurator: true,
    sortOrder: 24,
  },
  
  // White Quartzites
  {
    id: 'mont-blanc-quartzite',
    name: 'Mont Blanc Quartzite',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Pure white mountain majesty',
    characterTags: ['cool', 'calm'],
    swatchColor: '#FFFAFA',
    swatchImage: '/stones/marble/super-white-marble.jpg',
    isActiveInConfigurator: true,
    sortOrder: 25,
  },
  {
    id: 'infinity-white-quartzite',
    name: 'Infinity White Quartzite',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Endless white elegance',
    characterTags: ['cool', 'calm'],
    swatchColor: '#F8F8FF',
    swatchImage: '/stones/marble/star-white.jpg',
    isActiveInConfigurator: true,
    sortOrder: 26,
  },
  {
    id: 'alabastro-white-quartzite',
    name: 'Alabastro White Quartzite',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Alabaster-like translucency',
    characterTags: ['cool', 'calm'],
    swatchColor: '#FAEBD7',
    swatchImage: '/stones/marble/star-white.jpg',
    isActiveInConfigurator: true,
    sortOrder: 27,
  },
  {
    id: 'taj-mahal-quartzite',
    name: 'Taj Mahal Quartzite',
    family: 'marble',
    collection: 'vanta',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Indian palace inspiration',
    characterTags: ['warm', 'veined', 'statement'],
    swatchColor: '#F5F5DC',
    swatchImage: '/stones/marble/taj-mahal.jpg',
    isActiveInConfigurator: true,
    sortOrder: 28,
  },
  {
    id: 'alpine-quartzite',
    name: 'Alpine Quartzite',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Mountain-fresh white stone',
    characterTags: ['cool', 'calm'],
    swatchColor: '#F0F0F5',
    swatchImage: '/stones/marble/volakas-white.jpg',
    isActiveInConfigurator: true,
    sortOrder: 29,
  },
  {
    id: 'patagonia-quartzite',
    name: 'Patagonia Quartzite',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'South American wilderness beauty',
    characterTags: ['cool', 'veined'],
    swatchColor: '#E8E8E0',
    swatchImage: '/stones/marble/volakas-white.jpg',
    isActiveInConfigurator: true,
    sortOrder: 30,
  },
  {
    id: 'taj-royal-jade-quartzite',
    name: 'Taj Royal Jade Quartzite',
    family: 'marble',
    collection: 'vanta',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Royal jade with golden veins',
    characterTags: ['cool', 'veined', 'statement'],
    swatchColor: '#00A693',
    swatchImage: '/stones/marble/emerald-jade.jpg',
    isActiveInConfigurator: true,
    sortOrder: 31,
  },
  {
    id: 'votoria-regina-quartzite',
    name: 'Votoria Regina Quartzite',
    family: 'marble',
    collection: 'vanta',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Queen Victoria inspired elegance',
    characterTags: ['cool', 'dramatic', 'statement'],
    swatchColor: '#E0E0E8',
    swatchImage: '/stones/marble/elegant-grey.jpg',
    isActiveInConfigurator: true,
    sortOrder: 32,
  },
  
  // Pink/Rose Marbles
  {
    id: 'rose-rainbow',
    name: 'Rose Rainbow',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Rainbow of rose hues',
    characterTags: ['warm', 'veined'],
    swatchColor: '#FFB6C1',
    swatchImage: '/stones/marble/rose-rainbow.jpg',
    isActiveInConfigurator: true,
    sortOrder: 33,
  },
  {
    id: 'pink-crystal-quartzite',
    name: 'Pink Crystal Quartzite',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Crystal pink sparkle stone',
    characterTags: ['warm', 'dramatic'],
    swatchColor: '#FFD1DC',
    swatchImage: '/stones/marble/rose-rainbow.jpg',
    isActiveInConfigurator: true,
    sortOrder: 34,
  },
  {
    id: 'rosette',
    name: 'Rosette',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Delicate rose pattern marble',
    characterTags: ['warm', 'veined'],
    swatchColor: '#E8B4B4',
    swatchImage: '/stones/marble/calacatta-rosa.jpg',
    isActiveInConfigurator: true,
    sortOrder: 35,
  },
  {
    id: 'ceppo-breccia-rosa',
    name: 'Ceppo Breccia Rosa',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Pink conglomerate terrazzo',
    characterTags: ['warm', 'dramatic'],
    swatchColor: '#D8A0A0',
    swatchImage: '/stones/marble/rose-rainbow.jpg',
    isActiveInConfigurator: true,
    sortOrder: 36,
  },
  {
    id: 'ceppo-rosso',
    name: 'Ceppo Rosso',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Red terrazzo conglomerate',
    characterTags: ['warm', 'dramatic', 'statement'],
    swatchColor: '#CD5C5C',
    swatchImage: '/stones/marble/rose-rainbow.jpg',
    isActiveInConfigurator: true,
    sortOrder: 37,
  },
  {
    id: 'rosso-trentino',
    name: 'Rosso Trentino',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Italian red from Trentino',
    characterTags: ['warm', 'dramatic', 'statement'],
    swatchColor: '#A52A2A',
    swatchImage: '/stones/marble/rose-rainbow.jpg',
    isActiveInConfigurator: true,
    sortOrder: 38,
  },
  {
    id: 'levanto-rosso',
    name: 'Levanto Rosso',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Deep burgundy from Levanto',
    characterTags: ['warm', 'dramatic', 'statement'],
    swatchColor: '#722F37',
    swatchImage: '/stones/marble/dark-emperador.jpg',
    isActiveInConfigurator: true,
    sortOrder: 39,
  },
  
  // Blue Marbles
  {
    id: 'calcite-blue',
    name: 'Calcite Blue',
    family: 'marble',
    collection: 'vanta',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Rare blue calcite elegance',
    characterTags: ['cool', 'dramatic', 'statement'],
    swatchColor: '#6495ED',
    swatchImage: '/stones/marble/calcite-blue.jpg',
    isActiveInConfigurator: true,
    sortOrder: 40,
  },
  
  // Brown/Emperador Marbles
  {
    id: 'light-emprador',
    name: 'Light Emprador',
    family: 'marble',
    collection: 'core',
    tier: 'signature',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Light Spanish emperador',
    characterTags: ['warm', 'veined'],
    swatchColor: '#C4A484',
    swatchImage: '/stones/marble/light-emperador.jpg',
    isActiveInConfigurator: true,
    sortOrder: 41,
  },
  {
    id: 'dark-emperador',
    name: 'Dark Emperador',
    family: 'marble',
    collection: 'core',
    tier: 'signature',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Rich dark Spanish brown',
    characterTags: ['warm', 'veined', 'dramatic'],
    swatchColor: '#3D2B1F',
    swatchImage: '/stones/marble/dark-emperador.jpg',
    isActiveInConfigurator: true,
    sortOrder: 42,
  },
  {
    id: 'daino-reale',
    name: 'Daino Reale',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Royal deer beige marble',
    characterTags: ['warm', 'calm'],
    swatchColor: '#D2B48C',
    swatchImage: '/stones/marble/daino-reale.jpg',
    isActiveInConfigurator: true,
    sortOrder: 43,
  },
  {
    id: 'eurasian-wood-marble',
    name: 'Eurasian Wood Marble',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Wood grain pattern marble',
    characterTags: ['warm', 'veined'],
    swatchColor: '#8B7355',
    swatchImage: '/stones/marble/wooden-white.jpg',
    isActiveInConfigurator: true,
    sortOrder: 44,
  },
  {
    id: 'ancient-wood',
    name: 'Ancient Wood',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Fossilized wood appearance',
    characterTags: ['warm', 'veined', 'dramatic'],
    swatchColor: '#8B4513',
    swatchImage: '/stones/marble/wooden-white.jpg',
    isActiveInConfigurator: true,
    sortOrder: 45,
  },
  
  // Grey Marbles
  {
    id: 'elegant-grey',
    name: 'Elegant Grey',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Sophisticated grey elegance',
    characterTags: ['cool', 'calm'],
    swatchColor: '#808080',
    swatchImage: '/stones/marble/elegant-grey.jpg',
    isActiveInConfigurator: true,
    sortOrder: 46,
  },
  {
    id: 'london-smoke',
    name: 'London Smoke',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'London fog grey tones',
    characterTags: ['cool', 'calm'],
    swatchColor: '#6B6B6B',
    swatchImage: '/stones/marble/london-smoke.jpg',
    isActiveInConfigurator: true,
    sortOrder: 47,
  },
  {
    id: 'carpathian',
    name: 'Carpathian',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Mountain grey with character',
    characterTags: ['cool', 'veined'],
    swatchColor: '#696969',
    swatchImage: '/stones/marble/london-smoke.jpg',
    isActiveInConfigurator: true,
    sortOrder: 48,
  },
  
  // Black Marbles
  {
    id: 'grand-antique',
    name: 'Grand Antique',
    family: 'marble',
    collection: 'vanta',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Historic black and white drama',
    characterTags: ['cool', 'dramatic', 'statement'],
    swatchColor: '#1C1C1C',
    swatchImage: '/stones/marble/grand-antique.jpg',
    isActiveInConfigurator: true,
    sortOrder: 49,
  },
  {
    id: 'black-marinaci',
    name: 'Black Marinaci',
    family: 'marble',
    collection: 'vanta',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Deep black with pebble pattern',
    characterTags: ['cool', 'dramatic', 'statement'],
    swatchColor: '#0A0A0A',
    swatchImage: '/stones/marble/black-marinaci.jpg',
    isActiveInConfigurator: true,
    sortOrder: 50,
  },
  
  // Breccia/Conglomerate
  {
    id: 'breccia-cascade',
    name: 'Breccia Cascade',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Cascading breccia pattern',
    characterTags: ['warm', 'dramatic'],
    swatchColor: '#C8B896',
    swatchImage: '/stones/marble/daino-reale.jpg',
    isActiveInConfigurator: true,
    sortOrder: 51,
  },
  {
    id: 'breccia-deggito',
    name: 'Breccia Deggito',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Classic Italian breccia',
    characterTags: ['warm', 'dramatic'],
    swatchColor: '#C0A080',
    swatchImage: '/stones/marble/daino-reale.jpg',
    isActiveInConfigurator: true,
    sortOrder: 52,
  },
  {
    id: 'ceppo-bianco',
    name: 'Ceppo Bianco',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'White terrazzo conglomerate',
    characterTags: ['cool', 'calm'],
    swatchColor: '#E8E8E0',
    swatchImage: '/stones/marble/star-white.jpg',
    isActiveInConfigurator: true,
    sortOrder: 53,
  },
  {
    id: 'montage-quartzite',
    name: 'Montage Quartzite',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Mountain montage patterns',
    characterTags: ['cool', 'veined'],
    swatchColor: '#B8B8A8',
    swatchImage: '/stones/marble/elegant-grey.jpg',
    isActiveInConfigurator: true,
    sortOrder: 54,
  },
  {
    id: 'opera-darte',
    name: 'Opera Darte',
    family: 'marble',
    collection: 'vanta',
    tier: 'icon',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Artistic masterpiece stone',
    characterTags: ['warm', 'dramatic', 'statement'],
    swatchColor: '#A08070',
    swatchImage: '/stones/marble/daino-reale.jpg',
    isActiveInConfigurator: true,
    sortOrder: 55,
  },
  
  // Onyx
  {
    id: 'ivory-onyx',
    name: 'Ivory Onyx',
    family: 'marble',
    collection: 'vanta',
    tier: 'icon',
    finishOptions: ['polished'],
    shortDescription: 'Translucent ivory luxury',
    characterTags: ['warm', 'dramatic', 'statement'],
    swatchColor: '#FFFFF0',
    swatchImage: '/stones/marble/ivory-onyx.jpg',
    isActiveInConfigurator: true,
    sortOrder: 56,
  },
  {
    id: 'alba-pura-white-onyx',
    name: 'Alba Pura White Onyx',
    family: 'marble',
    collection: 'vanta',
    tier: 'icon',
    finishOptions: ['polished'],
    shortDescription: 'Pure white translucent onyx',
    characterTags: ['cool', 'dramatic', 'statement'],
    swatchColor: '#FFF8F0',
    swatchImage: '/stones/marble/ivory-onyx.jpg',
    isActiveInConfigurator: true,
    sortOrder: 57,
  },
  
  // Limestone
  {
    id: 'moca-cream-limestone',
    name: 'Moca Cream Limestone',
    family: 'marble',
    collection: 'terra',
    tier: 'signature',
    finishOptions: ['honed', 'matte'],
    shortDescription: 'Portuguese creamy limestone',
    characterTags: ['warm', 'calm', 'porous'],
    swatchColor: '#E0D8C8',
    swatchImage: '/stones/marble/moca-cream.jpg',
    isActiveInConfigurator: true,
    sortOrder: 58,
  },
  {
    id: 'lloret',
    name: 'Lloret',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished'],
    shortDescription: 'Spanish coastal stone',
    characterTags: ['warm', 'calm'],
    swatchColor: '#D8D0C0',
    swatchImage: '/stones/marble/moca-cream.jpg',
    isActiveInConfigurator: true,
    sortOrder: 59,
  },
  {
    id: 'leonardo',
    name: 'Leonardo',
    family: 'marble',
    collection: 'core',
    tier: 'atelier',
    finishOptions: ['honed', 'polished', 'matte'],
    shortDescription: 'Renaissance master inspiration',
    characterTags: ['warm', 'calm'],
    swatchColor: '#C8C0B0',
    swatchImage: '/stones/marble/arabella.jpg',
    isActiveInConfigurator: true,
    sortOrder: 60,
  },
];

// ============================================
// COMBINED STONE LIBRARY
// ============================================
export const STONE_LIBRARY: StoneLibraryEntry[] = [
  ...TRAVERTINE_STONES,
  ...MARBLE_STONES,
];

// ============================================
// HELPER FUNCTIONS
// ============================================

export function getStonesByFamily(family: StoneFamily): StoneLibraryEntry[] {
  return STONE_LIBRARY
    .filter(s => s.family === family && s.isActiveInConfigurator)
    .sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getStonesByCollection(collection: StoneCollection): StoneLibraryEntry[] {
  return STONE_LIBRARY
    .filter(s => s.collection === collection && s.isActiveInConfigurator)
    .sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getStonesByTier(tier: StoneTier): StoneLibraryEntry[] {
  return STONE_LIBRARY
    .filter(s => s.tier === tier && s.isActiveInConfigurator)
    .sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getStonesByTags(tags: CharacterTag[]): StoneLibraryEntry[] {
  return STONE_LIBRARY
    .filter(s => s.isActiveInConfigurator && tags.every(tag => s.characterTags.includes(tag)))
    .sort((a, b) => a.sortOrder - b.sortOrder);
}

export function searchStones(query: string): StoneLibraryEntry[] {
  const normalizedQuery = query.toLowerCase().trim();
  if (!normalizedQuery) return STONE_LIBRARY.filter(s => s.isActiveInConfigurator);
  
  return STONE_LIBRARY
    .filter(s => 
      s.isActiveInConfigurator && (
        s.name.toLowerCase().includes(normalizedQuery) ||
        s.shortDescription.toLowerCase().includes(normalizedQuery) ||
        s.characterTags.some(tag => tag.includes(normalizedQuery))
      )
    )
    .sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getStoneById(id: string): StoneLibraryEntry | undefined {
  return STONE_LIBRARY.find(s => s.id === id);
}

// Map stone library entry to legacy config format for backward compatibility
export function mapToLegacyStoneConfig(entry: StoneLibraryEntry) {
  return {
    id: entry.id,
    name: { nl: entry.name, en: entry.name },
    color: entry.swatchColor,
    roughness: entry.finishOptions.includes('matte') ? 0.6 : 0.4,
    metalness: 0.02,
    collection: entry.collection,
    priceMultiplier: entry.tier === 'icon' ? 2.5 : entry.tier === 'atelier' ? 1.6 : 1.0,
    available: entry.isActiveInConfigurator,
  };
}

// Statistics for debugging
export const STONE_LIBRARY_STATS = {
  total: STONE_LIBRARY.length,
  travertine: TRAVERTINE_STONES.length,
  marble: MARBLE_STONES.length,
  byCollection: {
    terra: STONE_LIBRARY.filter(s => s.collection === 'terra').length,
    vanta: STONE_LIBRARY.filter(s => s.collection === 'vanta').length,
    core: STONE_LIBRARY.filter(s => s.collection === 'core').length,
  },
  byTier: {
    signature: STONE_LIBRARY.filter(s => s.tier === 'signature').length,
    atelier: STONE_LIBRARY.filter(s => s.tier === 'atelier').length,
    icon: STONE_LIBRARY.filter(s => s.tier === 'icon').length,
  },
};
