// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-stones.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
import { STONE_LIBRARY } from "npm:@/lib/configurator/stone-library";
var list_stones_default = defineTool({
  name: "list_stones",
  title: "List stones",
  description: "List the natural stone catalog offered by SERA NORR (travertine and marble). Optionally filter by family, collection, or tier.",
  inputSchema: {
    family: z.enum(["travertine", "marble"]).optional().describe("Filter by stone family."),
    collection: z.enum(["terra", "vanta", "core"]).optional().describe("Filter by collection."),
    tier: z.enum(["signature", "atelier", "icon"]).optional().describe("Filter by tier."),
    activeOnly: z.boolean().optional().describe("If true, only return stones currently active in the 3D configurator.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ family, collection, tier, activeOnly }) => {
    const items = STONE_LIBRARY.filter(
      (s) => (!family || s.family === family) && (!collection || s.collection === collection) && (!tier || s.tier === tier) && (!activeOnly || s.isActiveInConfigurator)
    ).map((s) => ({
      id: s.id,
      name: s.name,
      family: s.family,
      collection: s.collection,
      tier: s.tier,
      finishOptions: s.finishOptions,
      description: s.shortDescription,
      characterTags: s.characterTags
    }));
    return {
      content: [{ type: "text", text: `Found ${items.length} stones.

${JSON.stringify(items, null, 2)}` }],
      structuredContent: { count: items.length, stones: items }
    };
  }
});

// src/lib/mcp/tools/get-atelier-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_atelier_info_default = defineTool2({
  name: "get_atelier_info",
  title: "Get atelier info",
  description: "Return SERA NORR contact and atelier information: phone, email, website, lead time and pricing starting points.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "SERA NORR",
      tagline: "Digital bespoke atelier \u2014 natural stone furniture",
      phone: "+31 6 83 99 11 58",
      email: "info@sera-norr.com",
      website: "https://sera-norr.com",
      leadTimeWeeks: "12\u201316",
      startingPrices: {
        diningTables: "from \u20AC3,000",
        coffeeTables: "from \u20AC1,950",
        currency: "EUR",
        note: "Prices shown are starting (vanaf) prices. Final price depends on stone, size and finish."
      },
      languages: ["nl", "en"]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/submit-contact-request.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
var submit_contact_request_default = defineTool3({
  name: "submit_contact_request",
  title: "Submit contact request",
  description: "Submit a contact / bespoke inquiry to the SERA NORR atelier. The team follows up by email within 1\u20132 business days.",
  inputSchema: {
    email: z2.string().email().describe("Contact email of the person making the request."),
    name: z2.string().min(1).max(100).optional().describe("Full name."),
    phone: z2.string().max(50).optional().describe("Phone number (optional)."),
    subject: z2.enum(["algemeen", "maatwerk", "samenwerking"]).optional().describe("Subject category: general question, bespoke, or partnership."),
    message: z2.string().min(1).max(5e3).describe("The message / inquiry content.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
  handler: async ({ email, name, phone, subject, message }) => {
    const env = globalThis.process?.env ?? {};
    const url = env.SUPABASE_URL;
    const serviceKey = env.SUPABASE_SERVICE_ROLE_KEY;
    if (!url || !serviceKey) {
      return {
        content: [{ type: "text", text: "Backend not configured." }],
        isError: true
      };
    }
    const supabase = createClient(url, serviceKey, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("form_submissions").insert({
      form_type: "contact",
      email: email.toLowerCase().trim(),
      name: name ?? null,
      phone: phone ?? null,
      subject: subject ?? "algemeen",
      message,
      metadata: { source: "mcp" }
    }).select("id").single();
    if (error) {
      return {
        content: [{ type: "text", text: `Failed to submit: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `Contact request received. The SERA NORR atelier will reply by email within 1\u20132 business days.`
        }
      ],
      structuredContent: { id: data.id, status: "received" }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "sera-norr-mcp",
  title: "SERA NORR Atelier",
  version: "0.1.0",
  instructions: "Tools for the SERA NORR digital bespoke atelier (natural stone furniture). Use `list_stones` to browse the travertine and marble catalog, `get_atelier_info` for contact details, lead time and starting prices, and `submit_contact_request` to send a bespoke or general inquiry to the atelier team.",
  tools: [list_stones_default, get_atelier_info_default, submit_contact_request_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
